// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201203232812_ExtendSeedDataMigration")]
    partial class ExtendSeedDataMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("character varying(50000)")
                        .HasMaxLength(50000);

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubjectId")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("character varying(50000)")
                        .HasMaxLength(50000);

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubjectId")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("api.Models.Alias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'100', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<double>("Wpm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Aliases");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Accuracy = 97.109999999999999,
                            DateOfCreation = new DateTime(2020, 12, 3, 23, 28, 11, 346, DateTimeKind.Utc).AddTicks(7279),
                            Name = "Kramer",
                            Points = 1631,
                            Rank = 1,
                            Time = 93304223L,
                            UserId = "1",
                            Wpm = 85.549999999999997
                        },
                        new
                        {
                            Id = 2L,
                            Accuracy = 95.689999999999998,
                            DateOfCreation = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(1384),
                            Name = "Bob_Sacamano",
                            Points = 238,
                            Rank = 2,
                            Time = 1388820L,
                            UserId = "2",
                            Wpm = 67.670000000000002
                        },
                        new
                        {
                            Id = 3L,
                            Accuracy = 95.659999999999997,
                            DateOfCreation = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(1473),
                            Name = "Bobby",
                            Points = 488,
                            Rank = 3,
                            Time = 2559302L,
                            UserId = "2",
                            Wpm = 73.549999999999997
                        });
                });

            modelBuilder.Entity("api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Biography")
                        .HasColumnType("character varying(800)")
                        .HasMaxLength(800);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PictureURL")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<long>("SelectedAliasId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1def1244-ecbb-4f8f-a2b8-98d74af9d5f8",
                            DateOfRegistration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kramer@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "KRAMER@EXAMPLE.COM",
                            NormalizedUserName = "COSMO_KRAMER",
                            PasswordHash = "AQAAAAEAACcQAAAAEJKU5y+PASUx8/BUnkAJVz4ZRNHET8X8SdxFAbkX2zp0i2j/cy9jWCurRoSYIsygzQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cb732bb5-8884-4039-a029-5d88b5d85be8",
                            SelectedAliasId = 1L,
                            TwoFactorEnabled = false,
                            UserName = "Cosmo_Kramer"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18088589-c097-4231-9cf0-5bcb536db104",
                            DateOfRegistration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.sacamano@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB.SACAMANO@EXAMPLE.COM",
                            NormalizedUserName = "BOB_SACAMANO",
                            PasswordHash = "AQAAAAEAACcQAAAAEOQ9+jydJUuh4B/jcdrPTY9J5fkU4ymEOPxpNaEKRvTJNedOoWDV/gV3pKrhelIq9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1b0a9706-9bff-4ae6-bfe4-cd6e8f24cf55",
                            SelectedAliasId = 3L,
                            TwoFactorEnabled = false,
                            UserName = "Bob_Sacamano"
                        });
                });

            modelBuilder.Entity("api.Models.Performance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'100', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AliasId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateOfCompletion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("ReplayData")
                        .HasColumnType("text");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AliasId");

                    b.HasIndex("SectionId");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(4673),
                            Points = 67,
                            ReplayData = "",
                            SectionId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6543),
                            Points = 99,
                            ReplayData = " ",
                            SectionId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6584),
                            Points = 258,
                            ReplayData = " ",
                            SectionId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6585),
                            Points = 129,
                            ReplayData = " ",
                            SectionId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6586),
                            Points = 84,
                            ReplayData = " ",
                            SectionId = 4L
                        },
                        new
                        {
                            Id = 6L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6587),
                            Points = 130,
                            ReplayData = " ",
                            SectionId = 5L
                        },
                        new
                        {
                            Id = 7L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6588),
                            Points = 33,
                            ReplayData = " ",
                            SectionId = 6L
                        },
                        new
                        {
                            Id = 8L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6589),
                            Points = 32,
                            ReplayData = " ",
                            SectionId = 7L
                        },
                        new
                        {
                            Id = 9L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6590),
                            Points = 43,
                            ReplayData = " ",
                            SectionId = 8L
                        },
                        new
                        {
                            Id = 10L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6591),
                            Points = 91,
                            ReplayData = " ",
                            SectionId = 9L
                        },
                        new
                        {
                            Id = 11L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6592),
                            Points = 298,
                            ReplayData = " ",
                            SectionId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            AliasId = 1L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6593),
                            Points = 65,
                            ReplayData = " ",
                            SectionId = 2L
                        },
                        new
                        {
                            Id = 13L,
                            AliasId = 2L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6593),
                            Points = 123,
                            ReplayData = " ",
                            SectionId = 3L
                        },
                        new
                        {
                            Id = 14L,
                            AliasId = 2L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6594),
                            Points = 320,
                            ReplayData = " ",
                            SectionId = 4L
                        },
                        new
                        {
                            Id = 15L,
                            AliasId = 3L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6596),
                            Points = 18,
                            ReplayData = " ",
                            SectionId = 5L
                        },
                        new
                        {
                            Id = 16L,
                            AliasId = 3L,
                            DateOfCompletion = new DateTime(2020, 12, 3, 23, 28, 11, 347, DateTimeKind.Utc).AddTicks(6597),
                            Points = 430,
                            ReplayData = " ",
                            SectionId = 6L
                        });
                });

            modelBuilder.Entity("api.Models.RawStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'100', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CorrectKeypressCount")
                        .HasColumnType("integer");

                    b.Property<int>("IncorrectKeypressCount")
                        .HasColumnType("integer");

                    b.Property<long>("PerformanceId")
                        .HasColumnType("bigint");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId");

                    b.ToTable("RawStats");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CorrectKeypressCount = 450,
                            IncorrectKeypressCount = 30,
                            PerformanceId = 1L,
                            Time = 900000L
                        },
                        new
                        {
                            Id = 2L,
                            CorrectKeypressCount = 450,
                            IncorrectKeypressCount = 30,
                            PerformanceId = 1L,
                            Time = 900000L
                        },
                        new
                        {
                            Id = 3L,
                            CorrectKeypressCount = 80,
                            IncorrectKeypressCount = 8,
                            PerformanceId = 1L,
                            Time = 58000L
                        },
                        new
                        {
                            Id = 4L,
                            CorrectKeypressCount = 140,
                            IncorrectKeypressCount = 5,
                            PerformanceId = 1L,
                            Time = 120000L
                        },
                        new
                        {
                            Id = 5L,
                            CorrectKeypressCount = 1020,
                            IncorrectKeypressCount = 20,
                            PerformanceId = 2L,
                            Time = 240000L
                        },
                        new
                        {
                            Id = 19L,
                            CorrectKeypressCount = 32000,
                            IncorrectKeypressCount = 1000,
                            PerformanceId = 16L,
                            Time = 3400000L
                        },
                        new
                        {
                            Id = 18L,
                            CorrectKeypressCount = 12000,
                            IncorrectKeypressCount = 80,
                            PerformanceId = 15L,
                            Time = 730000L
                        },
                        new
                        {
                            Id = 17L,
                            CorrectKeypressCount = 3211,
                            IncorrectKeypressCount = 89,
                            PerformanceId = 14L,
                            Time = 520000L
                        },
                        new
                        {
                            Id = 16L,
                            CorrectKeypressCount = 3200,
                            IncorrectKeypressCount = 100,
                            PerformanceId = 13L,
                            Time = 420000L
                        },
                        new
                        {
                            Id = 15L,
                            CorrectKeypressCount = 80,
                            IncorrectKeypressCount = 10,
                            PerformanceId = 12L,
                            Time = 1200L
                        },
                        new
                        {
                            Id = 14L,
                            CorrectKeypressCount = 5000,
                            IncorrectKeypressCount = 0,
                            PerformanceId = 11L,
                            Time = 700000L
                        },
                        new
                        {
                            Id = 13L,
                            CorrectKeypressCount = 510,
                            IncorrectKeypressCount = 10,
                            PerformanceId = 10L,
                            Time = 120000L
                        },
                        new
                        {
                            Id = 12L,
                            CorrectKeypressCount = 7888,
                            IncorrectKeypressCount = 311,
                            PerformanceId = 9L,
                            Time = 1000000L
                        },
                        new
                        {
                            Id = 11L,
                            CorrectKeypressCount = 890,
                            IncorrectKeypressCount = 100,
                            PerformanceId = 8L,
                            Time = 200000L
                        },
                        new
                        {
                            Id = 10L,
                            CorrectKeypressCount = 1000,
                            IncorrectKeypressCount = 12,
                            PerformanceId = 7L,
                            Time = 240000L
                        },
                        new
                        {
                            Id = 9L,
                            CorrectKeypressCount = 2322,
                            IncorrectKeypressCount = 76,
                            PerformanceId = 6L,
                            Time = 320000L
                        },
                        new
                        {
                            Id = 8L,
                            CorrectKeypressCount = 3299,
                            IncorrectKeypressCount = 34,
                            PerformanceId = 5L,
                            Time = 480000L
                        },
                        new
                        {
                            Id = 7L,
                            CorrectKeypressCount = 1233,
                            IncorrectKeypressCount = 32,
                            PerformanceId = 4L,
                            Time = 180000L
                        },
                        new
                        {
                            Id = 6L,
                            CorrectKeypressCount = 1020,
                            IncorrectKeypressCount = 20,
                            PerformanceId = 3L,
                            Time = 240000L
                        });
                });

            modelBuilder.Entity("api.Models.Section", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'100', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<long>("TextId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TextId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "A cold wind gusted through the night, across the snow-covered land where men had been killing one another for the past three days. The air was crisp, if not so icy as Lan expected for this time of year.",
                            Difficulty = 0,
                            Length = 202,
                            TextId = 3L,
                            Title = "The Hook"
                        },
                        new
                        {
                            Id = 2L,
                            Content = "The wide corridor outside of the Amyrlin's apartments was as cold as her sitting room had been, and full of drafts. Some were strong enough to ripple one or another of the long, heavy tapestries on the white marble walls. Atop the gilded stand-lamps between the bright wall hangings, the flames flickered, nearly blown out. The novices would be at their breakfast at this hour, and likely most of the other Accepted, too. For the moment, the hallways were empty save for Siuan and Moiraine. They walked along the blue runner, half the width of the corridor, taking advantage of the small protection the carpet gave from the chill of the floor tiles, a repeating pattern in the colors of all seven Ajahs. Moiraine was too stunned to speak. The faint sound of the trumpets still sounding barely registered on her. They turned the corner into a hallway where the floor tiles were white, the runner green. To their right, another wide, tapestry-hung corridor lined with stand-lamps spiraled gently upward, toward the Ajahs’ quarters, the visible portion floored in blue and yellow, with a runner patterned in gray and brown and red. Inside each Ajah’s quarters, the Ajah’s own color predominated, and some others might be missing altogether, but in the communal areas of the Tower, the colors of all the Ajahs were used in equal proportion. Irrelevant thoughts drifted through her head. Why equal, when some Ajahs were larger than others? Had they once been the same size? How could that have been achieved? A newly raised Aes Sedai chose her Ajah freely. Yet each Ajah had quarters of the same size. Irrelevant thoughts were better than...",
                            Difficulty = 0,
                            Length = 1642,
                            TextId = 3L,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 3L,
                            Content = "And yet, she knew the answer. What had to be the answer. Nothing else fit. But they felt no urgency. Taking the boy from his mother straightaway would be cruel. Maybe they thought they had years to find him, but if that was the case, they had not even seen the list yet, with so many entries lacking as much as a home village. Maybe they were waiting for its completion. She hoped there were other searchers, because Siuan reported Valera and Ludice were still in the Tower.",
                            Difficulty = 0,
                            Length = 474,
                            TextId = 3L,
                            Title = "Shreds of Serenity"
                        },
                        new
                        {
                            Id = 4L,
                            Content = @"Verily I say unto you, the era of the sword and axe is nigh, the era of the wolf's blizzard. The Time of the White Chill and the White Light is nigh, the Time of Madness and the Time of Contempt: Tedd Deireddh, the Time of End. The world will die amidst frost and be reborn with the new sun. It will be reborn of the Elder Blood, of Hen Ichaer, of the seed that has been sown. A seed which will not sprout but will burst into flame.
Ess'tuath esse! Thus it shall be! Watch for the signs! What signs these shall be, I say unto you: first the earth will flow with the blood of Aen Seidhe, the Blood of Elves...",
                            Difficulty = 0,
                            Length = 609,
                            TextId = 2L,
                            Title = "Prologue"
                        },
                        new
                        {
                            Id = 5L,
                            Content = @"^'It would not be an exaggeration to say,^' continued the wizard, ^'that you have moved us deeply, Master Dandilion. You have prompted us to reflection and thought; you have stirred our hearts. Allow me to express our gratitude, and our respect.^'
The troubadour stood and took a bow, sweeping the heron feather pinned to his fashionable hat across his knees. His apprentice broke off his playing, grinned and bowed too, until Dandilion glared at him sternly and snapped something under his breath. The boy lowered his head and returned to softly strumming his lute strings.",
                            Difficulty = 0,
                            Length = 574,
                            TextId = 2L,
                            Title = "Chapter One"
                        },
                        new
                        {
                            Id = 6L,
                            Content = @"Triss Merigold blew into her frozen hands, wriggled her fingers and murmured a magic formula. Her horse, a gelding, immediately reacted to the spell, snorting and turning its head, looking at the enchantress with eyes made watery by the cold and wind.
^'You've got two options, old thing,^' said Triss, pulling on her gloves. ^'Either you get used to magic or I sell you to some peasants to pull a plough.^'
The gelding pricked up its ears, snorted vapour through its nostrils and obediently started down the wooded mountainside. The magician leaned over in the saddle, avoiding being lashed by the frosty branches.
The magic worked quickly; she stopped feeling the sting of cold in her elbows and on her neck and the unpleasant sensation of cold which had made her hunch her shoulders and draw her head in disappeared. The spell, warming her, also muffled the hunger which had been eating at her for several hours.",
                            Difficulty = 0,
                            Length = 917,
                            TextId = 2L,
                            Title = "Chapter Two"
                        },
                        new
                        {
                            Id = 7L,
                            Content = @"^'Your fears were unfounded, entirely ungrounded.^' Triss grimaced, resting her elbows on the table. ^'The time when wizards used to hunt Sources and magically gifted children, tearing them from their parents or guardians by force or deceit, is long gone. Did you really think I might want to take Ciri away from you?^'
Lambert snorted and turned his face away. Eskel and Vesemir looked at Geralt, and Geralt said nothing. He continued to gaze off to the side, playing incessantly with his silver witcher medallion, depicting the head of a snarling wolf. Triss knew the medallion reacted to magic. On such a night as Midinvaerne, when the air itself was vibrating with magic, the witchers' medallions must be practically humming. It must be both irritating and bothersome.
^'No, child,^' Vesemir finally said. ^'We know you would not do such a thing.^'",
                            Difficulty = 0,
                            Length = 853,
                            TextId = 2L,
                            Title = "Chapter Four"
                        },
                        new
                        {
                            Id = 8L,
                            Content = "This book is a distillation and adaptation of over eight years’ worth of my technical articles and news report- ing for Ars Technica, and as such, it reflects the insights and information offered to me by the many thousands of readers who’ve taken the time to contact me with their feedback. Journalists, professors, students, industry professionals, and, in many cases, some of the scientists and engineers who’ve worked on the processors covered in this book have all contributed to the text within these pages, and I want to thank these correspondents for their corrections, clari- fications, and patient explanations. In particular, I’d like to thank the folks at IBM for their help with the articles that provided the material for the part of the book dealing with the PowerPC 970. I’d also like to thank Intel Corp., and George Alfs in particular, for answering my questions about the processors.",
                            Difficulty = 0,
                            Length = 912,
                            TextId = 1L,
                            Title = "Acknowledgments"
                        },
                        new
                        {
                            Id = 9L,
                            Content = "In the real world, a processor’s pipeline can be found in more conditions than just the two described so far: a full pipeline or a pipeline that’s being filled. Sometimes, instructions get hung up in one pipeline stage for multiple cycles. There are a number of reasons why this might happen - we’ll discuss many of them throughout this book - but when it happens, the pipeline is said to stall. When the pipeline stalls, or gets hung in a certain stage, all of the instructions in the stages below the one where the stall happened continue advancing normally, while the stalled instruction just sits in its stage, and all the instructions behind it back up.",
                            Difficulty = 0,
                            Length = 664,
                            TextId = 1L,
                            Title = "Pipeline Stalls"
                        });
                });

            modelBuilder.Entity("api.Models.Text", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'100', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("CoverURL")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfUpload")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string[]>("Genres")
                        .HasColumnType("text[]");

                    b.Property<string>("ISBN")
                        .HasColumnType("text");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Texts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Author = "Jon Stokes",
                            CoverURL = "https://images-na.ssl-images-amazon.com/images/I/81gwE7V6TJL.jpg",
                            DateOfUpload = new DateTime(2020, 12, 3, 23, 28, 11, 346, DateTimeKind.Utc).AddTicks(4339),
                            Genres = new[] { "Technology" },
                            ISBN = "978-1593276683",
                            Length = 1576L,
                            Title = "Inside the Machine"
                        },
                        new
                        {
                            Id = 2L,
                            Author = "Andrzej Sapkowski",
                            CoverURL = "https://images-na.ssl-images-amazon.com/images/I/51xAJZfjFwL._SX306_BO1,204,203,200_.jpg",
                            DateOfUpload = new DateTime(2020, 12, 3, 23, 28, 11, 346, DateTimeKind.Utc).AddTicks(5339),
                            Genres = new[] { "Fantasy", "Action & Adventure" },
                            ISBN = "978-0316029193",
                            Length = 2953L,
                            Title = "The Witcher - Blood of Elves"
                        },
                        new
                        {
                            Id = 3L,
                            Author = "Robert Jordan",
                            CoverURL = "https://images-na.ssl-images-amazon.com/images/I/517MXt9nqnL._SX308_BO1,204,203,200_.jpg",
                            DateOfUpload = new DateTime(2020, 12, 3, 23, 28, 11, 346, DateTimeKind.Utc).AddTicks(5352),
                            Genres = new[] { "Fantasy" },
                            ISBN = "978-0765345455",
                            Length = 2318L,
                            Title = "Wheel of Time - New Spring"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Alias", b =>
                {
                    b.HasOne("api.Models.ApplicationUser", "User")
                        .WithMany("Aliases")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("api.Models.Performance", b =>
                {
                    b.HasOne("api.Models.Alias", "Alias")
                        .WithMany("Performances")
                        .HasForeignKey("AliasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Section", "Section")
                        .WithMany("Performances")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.RawStats", b =>
                {
                    b.HasOne("api.Models.Performance", "Performance")
                        .WithMany("RawStats")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Section", b =>
                {
                    b.HasOne("api.Models.Text", "Text")
                        .WithMany("Sections")
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
